source 'https://rubygems.org'

gem 'zss'
gem 'settingslogic'
gem 'activerecord', require: 'active_record'
gem 'zss-commons', git: 'git@github.com:dadah/zss-commons.git'
gem 'msgpack'
group :development, :test do
  gem 'pry-byebug'
end

group :development do
  gem 'guard-rspec', require: false
end

group :test do
  gem 'sqlite3'
  gem 'rspec'
end

group :production do 
  gem 'pg'
end